apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nvidia-operator
  - local-path-provisioner
  # Uncomment if you need multi-node model support (LeaderWorkerSet):
  # - lws
