apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qwen3-4b

resources:
  - namespace.yaml
  - ../../_base-intel

patches:
  - path: patches/model-args.yaml
  - path: patches/pvc-size.yaml
